### ISSUE TITLE
MSBuildLocator with "private" installs of .NET SDK results in "A compatible .NET SDK was not found." errors

### ISSUE THREAD

**Issue by mcumming** [microsoft/MSBuildLocator#304]
Running a console application that uses the MSBuildLocator from a .NET SDK installed with the `install-dotnet` scripts results in the "A compatible .NET SDK was not found."

Repro Steps: https://github.com/mcumming/MSBuildLocator_PrivateDotnet
1. Clone the repository
2. Run the ./init.ps1 script to install a local .NET SDK
3. Run the ./test.ps1 script to build and run the test app. 
I tried to make the test work on both Windows and macOS, but I only really tested on macOS.

If you already have the version of the SDK installed globally that is installed in the ./cli-tools then the test does not produce the error

Additionally, if the `TestTool` project does not reference Microsoft.Extensions.Logging.8.0.0 then running the test will result in :
``` 
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Microsoft.Extensions.Logging.Abstractions, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
 ---> System.IO.FileLoadException: Could not load file or assembly '/Users/mcumming/repos/MSBuildLocator_PrivateDotnet/cli-tools/sdk/9.0.100-preview.6.24328.19/Microsoft.Extensions.Logging.Abstractions.dll'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: '/Users/mcumming/repos/MSBuildLocator_PrivateDotnet/cli-tools/sdk/9.0.100-preview.6.24328.19/Microsoft.Extensions.Logging.Abstractions.dll'
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
   at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)

   at Microsoft.CodeAnalysis.MSBuild.DiagnosticReporterLoggerProvider.CreateLoggerFactoryForDiagnosticReporter(DiagnosticReporter reporter)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace..ctor(HostServices hostServices, ImmutableDictionary`2 properties)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.Create(IDictionary`2 properties, HostServices hostServices)
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.Create(IDictionary`2 properties)
   at Program.<Main>$(String[] args) in /Users/mcumming/repos/MSBuildLocator_PrivateDotnet/src/Program.cs:line 52
   at Program.<Main>(String[] args)
```

Actual:
```
###  PATH was /usr/local/microsoft/powershell/7:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/opt/homebrew/opt/openjdk/bin:/opt/homebrew/opt/node@18/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/share/dotnet/tools:/Users/mcumming/.dotnet/tools:/usr/local/share/dotnet:/usr/local/share/dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands
###  PATH is 
###  DOTNET_HOST_PATH is 
###  Current Process is at /Users/mcumming/repos/MSBuildLocator_PrivateDotnet/cli-tools/dotnet
###  DOTNET_HOST_PATH is /Users/mcumming/repos/MSBuildLocator_PrivateDotnet/cli-tools/dotnet
###  sdkRoot is /Users/mcumming/repos/MSBuildLocator_PrivateDotnet/cli-tools
###  dotnetSdkVersion is /Users/mcumming/repos/MSBuildLocator_PrivateDotnet/cli-tools/sdk/9.0.100-preview.6.24328.19
###  msbuildSdkPath is /Users/mcumming/repos/MSBuildLocator_PrivateDotnet/cli-tools/sdk/9.0.100-preview.6.24328.19
A compatible .NET SDK was not found.

Requested SDK version: 9.0.100-preview.6.24328.19
global.json file: /Users/mcumming/repos/MSBuildLocator_PrivateDotnet/global.json

Installed SDKs:
6.0.422 [/usr/local/share/dotnet/sdk]
7.0.314 [/usr/local/share/dotnet/sdk]
7.0.316 [/usr/local/share/dotnet/sdk]
8.0.201 [/usr/local/share/dotnet/sdk]
8.0.204 [/usr/local/share/dotnet/sdk]
8.0.300 [/usr/local/share/dotnet/sdk]

Install the [9.0.100-preview.6.24328.19] .NET SDK or update [/Users/mcumming/repos/MSBuildLocator_PrivateDotnet/global.json] to match an installed SDK.

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found

###  Found 7 MSBuild instances
A compatible .NET SDK was not found.

Requested SDK version: 9.0.100-preview.6.24328.19
global.json file: /Users/mcumming/repos/MSBuildLocator_PrivateDotnet/global.json

Installed SDKs:
6.0.422 [/usr/local/share/dotnet/sdk]
7.0.314 [/usr/local/share/dotnet/sdk]
7.0.316 [/usr/local/share/dotnet/sdk]
8.0.201 [/usr/local/share/dotnet/sdk]
8.0.204 [/usr/local/share/dotnet/sdk]
8.0.300 [/usr/local/share/dotnet/sdk]

Install the [9.0.100-preview.6.24328.19] .NET SDK or update [/Users/mcumming/repos/MSBuildLocator_PrivateDotnet/global.json] to match an installed SDK.

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
###  Found MSBuild instance 9.0.100 at /Users/mcumming/repos/MSBuildLocator_PrivateDotnet/cli-tools/sdk/9.0.100-preview.6.24328.19
###  Found MSBuild instance 8.0.300 at /usr/local/share/dotnet/sdk/8.0.300
###  Found MSBuild instance 8.0.204 at /usr/local/share/dotnet/sdk/8.0.204
###  Found MSBuild instance 8.0.201 at /usr/local/share/dotnet/sdk/8.0.201
###  Found MSBuild instance 7.0.316 at /usr/local/share/dotnet/sdk/7.0.316
###  Found MSBuild instance 7.0.314 at /usr/local/share/dotnet/sdk/7.0.314
###  Found MSBuild instance 6.0.422 at /usr/local/share/dotnet/sdk/6.0.422
A compatible .NET SDK was not found.

Requested SDK version: 9.0.100-preview.6.24328.19
global.json file: /Users/mcumming/repos/MSBuildLocator_PrivateDotnet/global.json

Installed SDKs:
6.0.422 [/usr/local/share/dotnet/sdk]
7.0.314 [/usr/local/share/dotnet/sdk]
7.0.316 [/usr/local/share/dotnet/sdk]
8.0.201 [/usr/local/share/dotnet/sdk]
8.0.204 [/usr/local/share/dotnet/sdk]
8.0.300 [/usr/local/share/dotnet/sdk]

Install the [9.0.100-preview.6.24328.19] .NET SDK or update [/Users/mcumming/repos/MSBuildLocator_PrivateDotnet/global.json] to match an installed SDK.

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
###  Selected MSBuild instance 9.0.100 at /Users/mcumming/repos/MSBuildLocator_PrivateDotnet/cli-tools/sdk/9.0.100-preview.6.24328.19
###  Registered MSBuild instance 9.0.100 at /Users/mcumming/repos/MSBuildLocator_PrivateDotnet/cli-tools/sdk/9.0.100-preview.6.24328.19
###  Creating MSBuildWorkspace for net8.0
###  Opening project '/Users/mcumming/repos/MSBuildLocator_PrivateDotnet/src/TestTool.csproj'
###  Project 'TestTool' opened
```

Expected:
```
###  PATH was /usr/local/microsoft/powershell/7:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/opt/homebrew/opt/openjdk/bin:/opt/homebrew/opt/node@18/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/share/dotnet/tools:/Users/mcumming/.dotnet/tools:/usr/local/share/dotnet:/usr/local/share/dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands
###  PATH is 
###  DOTNET_HOST_PATH is 
###  Current Process is at /Users/mcumming/repos/MSBuildLocator_PrivateDotnet/cli-tools/dotnet
###  DOTNET_HOST_PATH is /Users/mcumming/repos/MSBuildLocator_PrivateDotnet/cli-tools/dotnet
###  sdkRoot is /Users/mcumming/repos/MSBuildLocator_PrivateDotnet/cli-tools
###  dotnetSdkVersion is /Users/mcumming/repos/MSBuildLocator_PrivateDotnet/cli-tools/sdk/9.0.100-preview.6.24328.19
###  msbuildSdkPath is /Users/mcumming/repos/MSBuildLocator_PrivateDotnet/cli-tools/sdk/9.0.100-preview.6.24328.19

###  Found 7 MSBuild instances

###  Found MSBuild instance 9.0.100 at /Users/mcumming/repos/MSBuildLocator_PrivateDotnet/cli-tools/sdk/9.0.100-preview.6.24328.19
###  Found MSBuild instance 8.0.300 at /usr/local/share/dotnet/sdk/8.0.300
###  Found MSBuild instance 8.0.204 at /usr/local/share/dotnet/sdk/8.0.204
###  Found MSBuild instance 8.0.201 at /usr/local/share/dotnet/sdk/8.0.201
###  Found MSBuild instance 7.0.316 at /usr/local/share/dotnet/sdk/7.0.316
###  Found MSBuild instance 7.0.314 at /usr/local/share/dotnet/sdk/7.0.314
###  Found MSBuild instance 6.0.422 at /usr/local/share/dotnet/sdk/6.0.422

###  Selected MSBuild instance 9.0.100 at /Users/mcumming/repos/MSBuildLocator_PrivateDotnet/cli-tools/sdk/9.0.100-preview.6.24328.19
###  Registered MSBuild instance 9.0.100 at /Users/mcumming/repos/MSBuildLocator_PrivateDotnet/cli-tools/sdk/9.0.100-preview.6.24328.19
###  Creating MSBuildWorkspace for net8.0
###  Opening project '/Users/mcumming/repos/MSBuildLocator_PrivateDotnet/src/TestTool.csproj'
###  Project 'TestTool' opened

```

**Comment by YuliiaKovalova** [comment]
Hi @mcumming,

By default, MSBuild.Locator doesn't resolve the installed local sdks, because these can be put in an arbitrary location.
But it's possible to workaround this by setting the local sdk path as one of environment variables that is checked by the tool, e.g/ `DOTNET_HOST_PATH`
https://github.com/microsoft/MSBuildLocator/blob/3315948d539edc39c7b3bf5473692b7e65ce4207/src/MSBuildLocator/DotNetSdkLocationHelper.cs#L225C68-L225C84

**Comment by YuliiaKovalova** [comment]
Close since a workaround was provided.
Feel free to reopen if you still have any questions.
